# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windowaviso.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_windowaviso(object):
    def setupUi(self, windowaviso):
        windowaviso.setObjectName("windowaviso")
        windowaviso.setWindowModality(QtCore.Qt.WindowModal)
        windowaviso.resize(400, 200)
        windowaviso.setModal(True)
        self.btnBoxAviso = QtWidgets.QDialogButtonBox(windowaviso)
        self.btnBoxAviso.setGeometry(QtCore.QRect(130, 140, 161, 32))
        self.btnBoxAviso.setOrientation(QtCore.Qt.Horizontal)
        self.btnBoxAviso.setStandardButtons(QtWidgets.QDialogButtonBox.No|QtWidgets.QDialogButtonBox.Yes)
        self.btnBoxAviso.setObjectName("btnBoxAviso")
        self.label = QtWidgets.QLabel(windowaviso)
        self.label.setGeometry(QtCore.QRect(180, 120, 61, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(windowaviso)
        self.label_2.setGeometry(QtCore.QRect(170, 30, 71, 71))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("img/5a81af7d9123fa7bcc9b0793.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(windowaviso)
        self.btnBoxAviso.accepted.connect(windowaviso.accept)
        self.btnBoxAviso.rejected.connect(windowaviso.reject)
        QtCore.QMetaObject.connectSlotsByName(windowaviso)

    def retranslateUi(self, windowaviso):
        _translate = QtCore.QCoreApplication.translate
        windowaviso.setWindowTitle(_translate("windowaviso", "Aviso"))
        self.label.setText(_translate("windowaviso", "Desea Salir?"))
