# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windowaviso.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_windowaviso(object):
    def setupUi(self, windowaviso):
        windowaviso.setObjectName("windowaviso")
        windowaviso.resize(360, 200)
        windowaviso.setModal(True)
        self.lblAviso = QtWidgets.QLabel(windowaviso)
        self.lblAviso.setGeometry(QtCore.QRect(150, 110, 61, 16))
        self.lblAviso.setObjectName("lblAviso")
        self.btnBoxAviso = QtWidgets.QDialogButtonBox(windowaviso)
        self.btnBoxAviso.setGeometry(QtCore.QRect(100, 140, 156, 23))
        self.btnBoxAviso.setStandardButtons(QtWidgets.QDialogButtonBox.No|QtWidgets.QDialogButtonBox.Yes)
        self.btnBoxAviso.setObjectName("btnBoxAviso")
        self.lblImageAviso = QtWidgets.QLabel(windowaviso)
        self.lblImageAviso.setGeometry(QtCore.QRect(140, 20, 71, 71))
        self.lblImageAviso.setText("")
        self.lblImageAviso.setPixmap(QtGui.QPixmap("img/5a81af7d9123fa7bcc9b0793.png"))
        self.lblImageAviso.setScaledContents(True)
        self.lblImageAviso.setObjectName("lblImageAviso")

        self.retranslateUi(windowaviso)
        QtCore.QMetaObject.connectSlotsByName(windowaviso)

    def retranslateUi(self, windowaviso):
        _translate = QtCore.QCoreApplication.translate
        windowaviso.setWindowTitle(_translate("windowaviso", "Dialog"))
        self.lblAviso.setText(_translate("windowaviso", "Desea Salir?"))
